[project]
name = "asgi-idempotency-header"
version = "0.2.0"
description = "Enable idempotent operations for your endpoints."
authors = [{ name = "Sondre Lillebø Gundersen", email = "sondrelg@live.no" }]
requires-python = ">=3.8,<4"
readme = "README.md"
# license = "BSD-3"
license = { text = "BSD-3" }
# license = { file = "LICENSE" }
maintainers = [{ name = "Patrick Gleeson", email = "pgleeson@spoton.com" }]
keywords = [
    "idempotence",
    "idempotency",
    "header",
    "fastapi",
    "starlette",
    "asgi",
    "middleware",
    "api",
    "endpoint",
    "http",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Framework :: AsyncIO",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Middleware",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "fastapi>=0.70.0",
    "redis>=4.2",
    "lupa",
    "starlette>=0.44.0",
]

[project.urls]
Homepage = "https://github.com/snok/asgi-idempotency-header"
Repository = "https://github.com/snok/asgi-idempotency-header"

[dependency-groups]
dev = [
    "pytest",
    "coverage",
    "pre-commit",
    "httpx",
    "pytest-cov",
    "pytest-asyncio",
    "orjson",
    "ujson",
    "fakeredis",
    "ruff>=0.15.14",
    "mypy>=1.14.1",
]


[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
    "idempotency_header_middleware",
    "pyproject.toml",
    "README.md",
    "LICENSE",
]
exclude = [".gitignore"]
# artifacts = ["locust/webui/dist"]

[tool.hatch.build.targets.wheel]
include = ["idempotency_header_middleware"]
# artifacts = ["locust/webui/dist"]


[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py314"

[tool.ruff.lint]
extend-select = ["E","F","I","UP"]
ignore = []

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = 3.13
show_error_codes = true
show_traceback = true
warn_unused_ignores = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_configs = true
warn_no_return = false
incremental = true
disallow_untyped_calls = true
disallow_untyped_defs = true
check_untyped_defs = true

[tool.pytest.ini_options]
addopts = "--cov=idempotency_header_middleware --cov-report term-missing"
testpaths = ["tests"]

[tool.coverage.run]
omit = ['idempotency_header_middleware/backends/base.py']

[tool.coverage.report]
show_missing = true
skip_covered = true
exclude_lines = ["if TYPE_CHECKING:", "pragma: no cover"]
